### ISSUE TITLE
Write the documentation for Get Discussion API of the Implementation Assignment

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#102]
Writing a clean and proper documentation for API's written is a critical skill since it's beneficial not only for the writer of the code for the future uses but also for other ones who will review or use the code later, so add your API getting discussions for an event in the [implementation assignment](https://moodle.boun.edu.tr/mod/assign/view.php?id=409101)  code and its documentation to the [Milestone Report 2 document](https://docs.google.com/document/d/18h_tSLL-ozRxbWTddxjbscwqDCv9LiqVZV7egKG3mhk/edit#heading=h.yvblr91yc8ro)

**Comment by 38programmer61** [comment]
It has been added to the document and the Milestone Report 2 has been submitted for grading.

**Comment by omersuve** [comment]
It had been reviewed and approved by the other teammates, good job.
Thanks for the contribution!
