### ISSUE TITLE
Prepare and update the Project Plan

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#117]
The aim of the issue is preparing an updated version of our Project Plan.

**Comment by bnbcfyh** [comment]
The project plan needs to be updated for the Milestone 2. 

We can add our meetings, and the steps of the development for both backend and frontend. Each meeting for the development of the Practice App shall be included in the updated project plan. Meeting notes for the each meeting can be found in our Wiki page, [here](https://github.com/bounswe/2021SpringGroup6/wiki).

**Comment by bnbcfyh** [comment]
The updated project plan is posted on our internal group and is expecting reviews before we add it to our report.

**Comment by omersuve** [comment]
The plan had been reviewed and added to the deliverables report.

**Comment by eye-78** [comment]
We reviewed it all together. Nice work. Thank you
