### ISSUE TITLE
Contribute to the Group Report

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#119]
- [x] Fill in the column of my personal effort.
- [x] Add the information about a public API that used in the app.
- [x] Review the parts ot the other teammates.
- [x] Add the codes of back-end API that I created.

**Comment by fileames** [comment]
Thanks for your effort, since report is done, and can be found [here](https://github.com/bounswe/2021SpringGroup6/blob/master/deliverables/M2_Report_Group6.pdf) we can close this issue.
