### ISSUE TITLE
Bug related to nonexistent event retrieval from database

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#120]
When I send a GET request to the endpoint(api/v1.0/events/<event_id>) for "getting an event by its id", I do not get the error return I expect to get(as I handled in the function), instead I take "Internal server error". Inside the function, first I check if the event id is valid, and then check if any event is retrieved from the database by checking if the event retrieved is None. What might be the problem?

**Comment by berkatil** [comment]
We should debug the code to understand the core problem

**Comment by eye-78** [comment]
> We should debug the code to understand the core problem

Sure. Let’s schedule a meeting. Discord?

**Comment by kataparuto** [comment]
Exactly, debugging would solve the problem for us.

**Comment by berkatil** [comment]
Discord is okay

**Comment by berkatil** [comment]
We met with Arda and Ekrem to debug it. We realized that the "if condition" to check if the event exists in the database was in the wrong place. That is , it was after the checking of the non-negativity of the event id. However, existence check should be before this. Hence, we fixed the code

**Comment by kataparuto** [comment]
It was a quick and highly efficient meeting. I would like to thank to Ekrem and Berk for their friendly help.

**Comment by eye-78** [comment]
Thank you guys. It’s always a pleasure to help each other
