### ISSUE TITLE
I restored my code that was accidentally deleted from the User Interface of the practice-app

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#122]

**Comment by omersuve** [comment]
In the **init.py** and **base.html**, the equipment part had been disconnected from the UI, but it has been fixed

**Comment by eye-78** [comment]
Very unlucky. I am so sorry. I wish I had reviewed all the tasks one again right before the deployment :(

**Comment by omersuve** [comment]
Thanks for your kindness!
It was my fault. I should have checked the UI before the deployment of the app.
