### ISSUE TITLE
See Feedback from User (My Father)

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#127]
Hi! I show our app to my father. He liked it! He found it useful and wanted to give feedback so that the app can seem more nicely. Here is the list:

- Form for specifying a date part changes when the default language of the browser. We may set the labels manually. @eye-78  @fileames 
- Whether icon can be more responsive. Background of the icon was always grey while he looked at the pages. @kataparuto 
- Sport type can be sorted alphabetically. It would be more user friendly. @eye-78 @fileames 
- Sport types may be more various. He could not find "karpuz yakalamaca" :) @fileames 
- Sports page should display all sports as default. It displays none of them as default. @fileames 
-  The concept of badge symbols is ambiguous. They have no corresponding value through the website. @berkatil 
- Search by name methods should be case insensitive @everyone

**Comment by fileames** [comment]
I could not agree with him more.
- For the date part, I realized some changes occur on different browsers and I think I needed to test it on multiple browsers. I will test it better next time.
- Sorting would be very useful and can be added as a new feature.
- I guess users should be able to add sports, "karpuz yakalamaca" sounds fun.
- Showing all sports as default would make more sense and can be implemented with one line change, I will add it later.

Thanks for getting feedback, they are very useful.
