### ISSUE TITLE
Onboarding of New Team Member

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#130]
A new team member @salihozcelik has joined our group and should go through the documents prepared last semester. 

A separate issue should be opened for the changes and unclear parts of the documents.

- [x] [Contributing](https://github.com/bounswe/2021SpringGroup6/wiki/Contributing)
- [x] [Requirements](https://github.com/bounswe/2021SpringGroup6/wiki/Project-Requirements)
- [x] Mockups
- [x] Project Plan

**Comment by salihozcelik** [comment]
I read the wiki pages, and created profile page.
