### ISSUE TITLE
Taking over the task of keeping Meeting Notes

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#131]
Elif Sema an I are going to upload notes for each general meeting by changing week by week

**Comment by fileames** [comment]
[Meeting Template](https://github.com/bounswe/2021SpringGroup6/wiki/Group-Meeting-Template) will be used for the meeting notes.

**Comment by omersuve** [comment]
I added the meeting notes for meetings [12](https://github.com/bounswe/2021SpringGroup6/wiki/Group-Meeting-12)-[15](https://github.com/bounswe/2021SpringGroup6/wiki/Group-Meeting-15)-[16](https://github.com/bounswe/2021SpringGroup6/wiki/Group-Meeting-16).
