### ISSUE TITLE
Review Sequence Diagram 9 And Make Necessary Changes For It

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#159]
Design is a critical phase for any software development project and it's a fact that as time passes, some project requirements change. Furthermore, it becomes easier to notice the problematic parts in the design phases; therefore, checking the work coming from the previous semester and doing necessary updates are very useful at this point since implementation will start soon. For sequence diagrams, each person will check his/her own work; consequently, please check the 9th one among [Sequence Diagrams](https://github.com/bounswe/2021SpringGroup6/wiki/Sequence-Diagrams).

**Comment by eye-78** [comment]
I have done the necessary modifications. You can see it [here](https://github.com/bounswe/2021SpringGroup6/wiki/Sequence-Diagrams#9-creating-an-event)

**Comment by 38programmer61** [comment]
It looks nice thanks.
