### ISSUE TITLE
Review Sequence Diagram 5 And Make Necessary Changes For It

### ISSUE THREAD

**Issue by salihozcelik** [bounswe/2021SpringGroup6#161]
- Database access should be added(for every step)
- Dashed lines should be added from class boxes

**Comment by MercerFrey** [comment]
I made the necessary changes and the updated sequence diagram can be found here [link](https://github.com/bounswe/2021SpringGroup6/wiki/Sequence-Diagrams) as the 5. Sequence Diagram. (Adding Participants)
