### ISSUE TITLE
Change the User model

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#185]
Since we decided to use  django authentication system, we need to change our User model.
It should inherit `django.contrib.auth.models.AbstractBaseUser`, then we need to add our fields. Additionally the source code of `django.contrib.auth.models.AbstractUser` may be useful for inspiration, it is [here](https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/models/)

Resources that I looked at for this:
https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project
https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/models/
https://stackoverflow.com/questions/68425636/should-i-use-abstractbaseuser-or-abstractuser
https://stackoverflow.com/questions/67452838/django-remove-unwanted-user-fields-in-models-using-abstractuser

**Comment by fileames** [comment]
Since using Django authentication is a must to have a secure authentication system, I think we can take the actions needed. I am assigning you to the issue. Thanks for pointing this out.

**Comment by berkatil** [comment]
Sorry, the path that I provided is out of date. The correct one is `django.contrib.auth.base_user.AbstractBaseUser`

**Comment by fileames** [comment]
Thanks, the related pull request is merged.
