### ISSUE TITLE
Review Sequence Diagram 4 And Make Necessary Changes For It 

### ISSUE THREAD

**Issue by MercerFrey** [bounswe/2021SpringGroup6#189]
- Filter class should be checked (filterEvents should be underlined)
- It should be checked that whether Filter class returns anything to the user or not

**Comment by fileames** [comment]
I made the necessary changes:
- I made the SearchController functions static functions.
- For the object creation, I looked to some resources (such as [this](https://creately.com/blog/diagrams/sequence-diagram-tutorial/ )) and I think this is the correct way.
New diagram can be found here: https://github.com/bounswe/2021SpringGroup6/wiki/Sequence-Diagrams#4-searching-and-filtering-events

**Comment by MercerFrey** [comment]
It looks fine. Thank you.
