### ISSUE TITLE
Review Sequence Diagram 8: Sending request to attend an event

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#190]
The critics from last meeting:

* Information from database should be returned with an arrow.
* Insert arrow should be positioned lower
* Dashed lines should be added from Event class
* A note regarding an assumption about event is already found should be added under the picture.

**Comment by kataparuto** [comment]
I have completed the necessary changes.

- The response from the database now returns with a purple arrow
- Insert arrow is now in a lower position vertically.
- Dashed lines are added to the box of the Event class.
- A note has been added to the bottom which states that it is assumed that an event has already been found.
- A semicolon has been prepended to the "Event" class title.

**Comment by eye-78** [comment]
Nice work. Thank you
