### ISSUE TITLE
Construct The Project Structure For Front-End

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#193]
Constructing the structure of the project is the first step for any project and it's necessary to start the implementation. For front-end, React will be used; therefore, firstly, open a new directory for front-end and define a new React project in it so that all the members of the front-end team can contribute to it.

**Comment by 38programmer61** [comment]
I have done the work and opened a [pull request](https://github.com/bounswe/2021SpringGroup6/pull/194). After the review is done, if everything is OK, it can be merged.

**Comment by eye-78** [comment]
We reviewed the requests and merged them. Thanks for your effort
