### ISSUE TITLE
Merging the correct branch into frontend main

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#199]
@38programmer61 constructed the project. I will work on navigation and probably fork some of the branches that Musa created. I suggest merging -and also forking- only the latest branch would be sufficient. What are your opinions?

**Comment by salihozcelik** [comment]
I've merged the latest branch, and going to work on that branch

**Comment by eye-78** [comment]
Ok, let's keep moving from prepare_footer branch
