### ISSUE TITLE
Request handling management should be determined

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#203]
Starting from login page, we need to send http requests to the backend or other resources. We can use third party packages such as [axios](https://www.npmjs.com/package/axios). Axios lets us build interceptors so that we do not need to specify tokens and other necessary info in the request header repetitively. What are your thoughts?

**Comment by 38programmer61** [comment]
I think Axios looks OK.

**Comment by eye-78** [comment]
Ok. I will implement interceptors so that we do not have to add headers every time
