### ISSUE TITLE
Login/Register page implementation

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#204]
We do not have a design for login/register page but you may look at bootstrap's examples. 

* Page should start with login card
* There should be two links. One for forget password, one for register
* When register link is clicked, card for registration should be displayed. It may be a redirection or just a rerender, up to you
* When forgot password link is clicked, card for password reset should be displayed. Because password reset is a two-phase process, it may be a redirection. Talk to @salihozcelik

**Comment by 38programmer61** [comment]
Actually this part was @salihozcelik 's responsibility in the project plan, so probably a confusion has occured; therefore, I am changing the assignee.

**Comment by salihozcelik** [comment]
I have implemented the code, you can see it in the branch front/login_page
