### ISSUE TITLE
Reset password page implementation

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#205]
We do not have a design for reset password page but you may look at bootstrap's examples.

* Page should start with reset password card. Email info is requested
* Email structure validation can be done in that stage. That is, before sending http request
* Then card should change and it should start a counter. Reset password key should be provided within this time
* Validation of the key should be controlled by backend. The page should display the response coming from backend (e.g. "reset is successfull", "invalid key")
* When the reset is done, it should be redirected to login page. Depending on the implementation, it may be a route path change or rendering the login page card

**Comment by 38programmer61** [comment]
Actually this part was my responsibility in the project plan, so probably a confusion has occured; therefore, I am changing the assignee.

**Comment by 38programmer61** [comment]
As front-end team we've decided to keep this part simpler. It will be like the following. A person who forgot the password will provide an email. Then if email is valid, the person's new password will be sent to that email and the person will be informed.

**Comment by 38programmer61** [comment]
Currently it was implemented as mentioned. The details can be found in the [merge request](https://github.com/bounswe/2021SpringGroup6/pull/235).

**Comment by eye-78** [comment]
It would be nice if the page's color palette is in harmony with the general color palette. Nevertheless, the issue can be closed now. Please take a look at the colors when you are available
