### ISSUE TITLE
Profile Page Implementation

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#206]
One of the most essential parts for a web project is the homepage. It's very critical since it's the first part with which a user interacts. The content that will be available in this page is explained in 1.2.4 Profile Page section of the [project requirements](https://github.com/bounswe/2021SpringGroup6/wiki/Project-Requirements). Using react-bootstrap can be useful to get an idea about example works done for that task.

**Comment by eye-78** [comment]
Started working on it. Branc name is front/profile_page
At first stage I only implement for the current user's own profile page. Then I will create a custom path handler that shows other users' profile pages. It should be checked neither of the users are blocked

**Comment by eye-78** [comment]
I am waiting for reviews #242

**Comment by eye-78** [comment]
My branch includes

* Page layout such as header placement, sidebar placement and footer
* Sidebar functionality. I.e. toggling
* Profile page management. Displaying and modifying profile attributes
