### ISSUE TITLE
Decide Schema For Sports

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#233]
We should decide on a schema to represent the sports on our application. The most general type is [Thing](https://schema.org/Thing) but a more specific type would be better. I think we can use [PhysicalActivity](https://schema.org/PhysicalActivity) type with category as the type of the sport such as "football".    
After deciding, get sports endpoint and knows about field under get user endpoint should be fixed.

Related issues: #219 #179

**Comment by berkatil** [comment]
We have decided to go with Thing in get sports endpoint and with PropertyValue in get user endpoint to return skill levels of the user

**Comment by fileames** [comment]
Sport schema related pull request is merged. "Thing" will be used for sports.
