### ISSUE TITLE
Android Design - Home page

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#239]
The layout of the homepage should be designed. Later, the functionalities will be added.

**Comment by kataparuto** [comment]
The initial layout of the main page is created. However, no events are shown on the page right now. It will be implemented too.

**Comment by omersuve** [comment]
This homepage should be implemented by adding attending events of the logged in user.

**Comment by kataparuto** [comment]
The design is decided and the [issue](https://github.com/bounswe/2021SpringGroup6/issues/390) for the implementation here.
