### ISSUE TITLE
Android - Sign up functionality

### ISSUE THREAD

**Issue by MercerFrey** [bounswe/2021SpringGroup6#246]
Sign up functionality should be implemented. Layout was almost ready however it does not work and the necessary functionality of it should be added.

**Comment by omersuve** [comment]
I have completed the register operation and I pushed the recent code

**Comment by omersuve** [comment]
[Pull Request](https://github.com/bounswe/2021SpringGroup6/pull/281)
[Merge Commit](https://github.com/bounswe/2021SpringGroup6/commit/d4928006896a651aca8d6f762f8c30a9eab9e880#diff-f60ed56a9c8275894022fe5a7a1625c33bdb55b729bb4e38962af4d1613eda25)

**Comment by omersuve** [comment]
Bugs fixed and folders are located appropriately
[New PR](https://github.com/bounswe/2021SpringGroup6/pull/285)
