### ISSUE TITLE
Creating a scenario for searching and joining an event

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#27]
Create a scenario for searching and joining an event.
- Write the scenario using [Scenario Template](https://github.com/bounswe/2021SpringGroup6/wiki/Scenario-Template)

**Comment by uskudarli** [comment]
Don't forget to include descriptions. Among several other things you probably want to have a template for scenarios, so that scenarios are written in a consistent manner.

As for labels this is part of requirements (elicitation) so it would be good to indicate it.

**Comment by berkatil** [comment]
you can use this [Scenario Template](https://github.com/bounswe/2021SpringGroup6/wiki/Scenario-Template)

**Comment by kataparuto** [comment]
Decided to divide into two scenarios and created, 
1. [Search an Event Scenario](https://github.com/bounswe/2021SpringGroup6/wiki/Search-an-Event-Scenario)
2. [Send Request to Attend an Event Scenario](https://github.com/bounswe/2021SpringGroup6/wiki/Send-Request-to-Attend-an-Event-Scenario)

**Comment by eye-78** [comment]
Nice job. Thank you!
