### ISSUE TITLE
Participation Selection Page For Front-End

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#276]
One of the essential parts of the project is events and being able to select people who will participate in an event is a necessity for the owner of the event. Therefore, it ought to be implemented. It had better provide functionalities such as accepting and rejecting candidates for an event. [The following API](https://github.com/bounswe/2021SpringGroup6/issues/267) might be useful too.

**Comment by salihozcelik** [comment]
Its implemented.
