### ISSUE TITLE
Add predefined badges into the System

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#287]
Before our API runs supported badges should be added to the system similar to sports.

**Comment by berkatil** [comment]
it works well, thanks

**Comment by fileames** [comment]
We decided on some badges from the Wikidata on one of our lab meetings and I took notes of it. Then I added these to a data file with their Wikidata ids to add to system. The script works on start of the server and these badges are added to the system. 
These badges can be found [here](https://github.com/bounswe/2021SpringGroup6/blob/master/back-end/sports_platform/sports_platform_api/data/badges.py).
