### ISSUE TITLE
Modify Get Event Endpoint to get Badges related to it

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#288]
You should modify get event endpoint such that badges that can be retrieved via that event should be retrieved and added into the db.

**Comment by berkatil** [comment]
thanks for the effort

**Comment by fileames** [comment]
I implemented the endpoint. Its documentation can be found [here](https://github.com/bounswe/2021SpringGroup6/wiki/Squad-Game-API-Documentation#eventsevent_idbadges-get---get-event-badges).
