### ISSUE TITLE
Create a DB model For Badges

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#289]
Badge table should be created. Table name should be "badges". The fields should be badge_id, badge_name, image_url.

**Comment by fileames** [comment]
Badges model is created. Image is not implemented yet since front-end team did not start working on it. Curent model can be found [here](https://github.com/bounswe/2021SpringGroup6/blob/master/back-end/sports_platform/sports_platform_api/models/badge_models.py#L3).
