### ISSUE TITLE
Create mock-up for searching and joining an event

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#29]
Prepare mock-up for searching and joining an event.

**Comment by kataparuto** [comment]
Mock-up for searching an event in Web:
[Link](https://github.com/bounswe/2021SpringGroup6/wiki/Search-an-event--website-mock-up)
Mock-up for searching an event in Android:
[Link](https://github.com/bounswe/2021SpringGroup6/wiki/Search-an-event-mobile-mock-up)
Mock-up for joining an event in Web:
[Link](https://github.com/bounswe/2021SpringGroup6/wiki/Send-request-to-attend-an-event-website-mock-up)
Mock-up for joining an event in Android:
[Link](https://github.com/bounswe/2021SpringGroup6/wiki/Send-request-to-attend-an-event-website-mobile-mock-up)

**Comment by eye-78** [comment]
Nice job. Thank you!
