### ISSUE TITLE
Create a DB model for user badge relation

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#290]
To store retrieved badges for each user we need to define a table. The table name should be user_badges. The fields are user_id, badge_id and event_id. event_id is the event at which the user retrieves that badge

**Comment by fileames** [comment]
For this purpose, I created two databases. One for badges that are obtained by participating an event and one of badges given by other users. This way whenever a creator adds a badge to an event, it is added to the event database and only one row is created, not separate rows for each participants. I believe this makes the implementation easier and improves efficiency.
