### ISSUE TITLE
Create an endpoint to get all events that a user created

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#294]
We need to list all the events to a user so that they can easily find and modify/delete these events.

The appropriate info of an element of the list contains:

Most important:   
- [ ] Event title
- [ ] Event id
   
   
Nice to have:
- [ ] Creation date
- [ ] Last update date
- [ ] Number of participants

**Comment by berkatil** [comment]
Thanks for reporting this @eye-78. Actually via using "events/searches" endpoint with specifying "creator" field, this functionality is provided, so I do not think there is need to create an additional endpoint for this. Is it okay with you?

**Comment by eye-78** [comment]
> Thanks for reporting this @eye-78. Actually via using "events/searches" endpoint with specifying "creator" field, this functionality is provided, so I do not think there is a need to create an additional endpoint for this. Is it okay with you?

I'll use this endpoint. Thank you
