### ISSUE TITLE
A bug about /events POST - Create Event endpoint

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#302]
I was using Ubuntu 18.04. When I tried to access the endpoint by using postman in order to understand how it works, it behaved strangely for a certain request. More information is like the following. 
The problem has occurred when I send a post request to 3.20.232.108:8080/events endpoint with the following body.
{   
    "name" : "Maç", 
    "sport" : "soccer", 
    "description" : "Her seviyeden insan gelebilir", 
    "startDate" : "2021-12-28T10:00+03:00",
    "latitude" : 41.084,
    "longitude" : 29.051,
    "minimumAttendeeCapacity" : "10", 
    "maximumAttendeeCapacity" : "12", 
    "maxSpectatorCapacity" : "24", 
    "minSkillLevel" : "1", 
    "maxSkillLevel" : "3",
    "acceptWithoutApproval" : "false",
    "duration": 60
} 

It returned with 500 Internal Server Error.

Authentication was OK. Also the error wasn't about it; therefore, I don't think that the problem was about that point. Nevertheless, a similar input which is like the following

![Screenshot from 2021-12-11 15-07-03](https://user-images.githubusercontent.com/56412256/145690007-3d40a436-bbd4-44be-b072-a39e03668fbf.png)

causes the expected behavior which is opening the new event, so could you take a look at the point because I think there isn't any important difference that will cause a different behavior between these 2 inputs?

**Comment by fileames** [comment]
I checked the problem and it is about the reverse geocoding API(Nominatim) we are using. It returns different labels for different addresses. For example on an example, I tried "Trabzon" was on the "state" field but on the example you tried "Istanbul" is in the "province" field and there isn't a "state" field. I will check the documentation and fix the bug. Thanks for pointing it out.

**Comment by fileames** [comment]
Related changes are merged and deployed. Can you confirm that the issue is solved?

**Comment by 38programmer61** [comment]
It has been resolved. The mentioned input opens a new event now, which was the expected behavior. Thanks.
