### ISSUE TITLE
Endpoint for interest, acceptance, spectating information about a user may be modified

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#304]
Hi,
I'm listing events that a user sends a request to join. To do that, I need more information than now. For example, I think I should display time of the event, number of participants etc. To do that, I can send get requests for every events. However, it would be costly for us. Do you consider modifying these endpoints?

**Comment by fileames** [comment]
I can update the enpoint. Can you give a list of the properties of the event that you need to be returned?

**Comment by eye-78** [comment]
> I can update the enpoint. Can you give a list of the properties of the event that you need to be returned?

Thank you. Here is the current info I'm consuming:
* event id
* name
* sport type
* address
* starting date
* maximum number of participants


Actually why dont you use the same format as events/search?
