### ISSUE TITLE
Android Bug - User Registration

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#314]
The user sign-up functionality is not implemeted appropriately, there is a bug.
The connection with the backend should be reviewed.

**Comment by omersuve** [comment]
I reviewed the issue and fixes wtih this commit: [Commit](https://github.com/bounswe/2021SpringGroup6/commit/5f3476c109d39c2473fc04926ff359732ea9640f)

**Comment by kataparuto** [comment]
User registration functionality is done.
The related [commit](https://github.com/bounswe/2021SpringGroup6/commit/5309a57e1989ba472d957aa13472ce610edd3897)
