### ISSUE TITLE
Android Design - Logout and Home buttons in Profile Page

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#317]
Logout and Home buttons should be added in the profile page of the logged in user.

**Comment by kataparuto** [comment]
I think the logout button should be in the homepage, and the home button should always be visible at the below.

**Comment by omersuve** [comment]
The visibility of home button is a good idea, that is a practical way.
We may discuss where the logout button should be in, profile page or homepage.

**Comment by kataparuto** [comment]
The design is already decided and the implementation of the design is already finished. This issue should be closed.
