### ISSUE TITLE
Android - Navigating Home and Logout operations

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#318]
Log Out operation and the operation of going back to the homepage should be implemented. Both of these operations are in the profile page of the logged in user, thereby should be implemented together.

**Comment by kataparuto** [comment]
We have reviewed this feature and finally decided that the logout button should be in the home page. Also, as discussed [here](https://github.com/bounswe/2021SpringGroup6/issues/365), there will be three tabs(home page, search, profile page) below with which user will easily be able to navigate between these three pages. Hence, there is no need to put an additional navigation functionality to profile page.

**Comment by omersuve** [comment]
Yes, as we discussed the design and implementation for the best user experience, logout button in homepage would be better
