### ISSUE TITLE
Update mockup page

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#32]
Update your mockup scenario according to instructions given by TA.
Add photo upload section
Add link to fields

**Comment by eye-78** [comment]
[Event Creation Scenario](https://github.com/bounswe/2021SpringGroup6/wiki/Event-Creation-Scenario)
[Event Creation Mockup (Website)](https://github.com/bounswe/2021SpringGroup6/wiki/Event-Creation-Mockup-(Website))
[Event Creation Mockup (Mobile)](https://github.com/bounswe/2021SpringGroup6/wiki/Event-Creation-Mockup-(Mobile))

**Comment by fileames** [comment]
Updates are clear. Closing the issue.
