### ISSUE TITLE
Add field requirements

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#33]
We should specify fileds' attributes.
Fields are displayed via map
Photos and comments can be posted to field pages
The page is useful because we do not have to upload field photos every time an organizator creates an event

**Comment by eye-78** [comment]
[Fields part in requirements page](https://github.com/bounswe/2021SpringGroup6/wiki/Project-Requirements#15-fields)

**Comment by fileames** [comment]
All information from the customer added, I am closing the issue
