### ISSUE TITLE
Android Feature - Event Detail Page design and navigation implementation

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#350]
The event page should be designed and the necessary functionalities should be implemented.

**Comment by omersuve** [comment]
User does not have to be a logged in User.
User should be able to press the search button, and search the events by their name.

**Comment by kataparuto** [comment]
The design of the Event Detail Page is finished, also the navigation is handled. The related pull request: https://github.com/bounswe/2021SpringGroup6/pull/406

**Comment by kataparuto** [comment]
The related pull request: https://github.com/bounswe/2021SpringGroup6/pull/406
