### ISSUE TITLE
Android - Search page review

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#351]
The user will be able to search events, users and equipments from the same page. The changes will be made.

**Comment by omersuve** [comment]
The design should be like what you have written. We may look at our mock up, if we are confused. [Related Mockup](https://github.com/bounswe/2021SpringGroup6/wiki/Search-an-event-mobile-mock-up)

**Comment by kataparuto** [comment]
The fragment for search page is created(SearchFragment). The layout is created for the SearchFragment. As decided, the search for events, users and equipments will be done by the user in this fragment. 
The related [PR)(https://github.com/bounswe/2021SpringGroup6/pull/392)
The related [commit](https://github.com/bounswe/2021SpringGroup6/pull/392/commits/aa386b5b1b773c61212cc28b61a283681eab66b1)
