### ISSUE TITLE
Add More Visibility Options

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#356]
Based on the requirement:
1.2.4.4 Users shall be given the option to show and hide the full name, profile picture, age, **user location**, **skill level for each sport**, **personal badges**, **previously attended events**, **previously created events**.

Visibility option for the bold features must be added.

**Comment by berkatil** [comment]
I decided to not implement this functionality for "previously attended events" because we do not have any endpoint to return them. Is this fine?

**Comment by fileames** [comment]
Implemented on #426
