### ISSUE TITLE
Android - Adding Attending Events to Home page 

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#366]
Homepage of the logged in User should be implemented.
We should add the attending events of the logged in User.

**Comment by kataparuto** [comment]
The RecyclerView to view adding attending events is created. The related [PR](https://github.com/bounswe/2021SpringGroup6/pull/379), the related [commit](https://github.com/bounswe/2021SpringGroup6/pull/379/commits/21210e0f802ad7dcd0c189e8fd1294acff91ecc8)

**Comment by kataparuto** [comment]
The related endpoint is integrated to the code. The related [PR](https://github.com/bounswe/2021SpringGroup6/pull/380), the related [commit](https://github.com/bounswe/2021SpringGroup6/pull/380/commits/bf5d16ac7054eca50ffb62018a11664c27111c7e)

**Comment by omersuve** [comment]
Good work!
