### ISSUE TITLE
Android - Adding Created Events to Home page

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#367]
Homepage of the logged in User should be implemented.
We should add the created events of the logged in User.

**Comment by omersuve** [comment]
It is done
[PR](https://github.com/bounswe/2021SpringGroup6/pull/430)

**Comment by kataparuto** [comment]
I have successfully implemented it. The related PR: https://github.com/bounswe/2021SpringGroup6/pull/430

**Comment by kataparuto** [comment]
I have successfully implemented it. The related PR : https://github.com/bounswe/2021SpringGroup6/pull/430
