### ISSUE TITLE
Create a Sequence Diagram for Unblocking a User

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#37]
It should be based on the class diagram and the use case diagram.

**Comment by omersuve** [comment]
[Sequence Diagram](https://user-images.githubusercontent.com/45875987/116467528-75278c00-a878-11eb-8b20-389684b3ecb4.png) for unblocking operation is created and added to wiki.

**Comment by berkatil** [comment]
It would be good if you can add the database access

**Comment by omersuve** [comment]
Database access is added.

**Comment by berkatil** [comment]
It represents the operation nicely, thanks!
