### ISSUE TITLE
Android Feature - Event search implementation

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#370]
On event search, the results(events) should be shown in a RecyclerView vertically. The user should be able to navigate to event pages by clicking them.

**Comment by omersuve** [comment]
Relevant issues regarding this implementation:
[Event Card Design](https://github.com/bounswe/2021SpringGroup6/issues/319)
[Event RecyclerView](https://github.com/bounswe/2021SpringGroup6/issues/321)

**Comment by kataparuto** [comment]
The search results are listed on a new fragment.

**Comment by kataparuto** [comment]
The related [PR](https://github.com/bounswe/2021SpringGroup6/pull/398).  Filters for event search will also be added, including location based search(map filter).

**Comment by kataparuto** [comment]
The filters are added to event search. Now the user is able to filter events based on many filters such as location(from the map), sport type etc. in event search. Here is the related pull request https://github.com/bounswe/2021SpringGroup6/pull/417.
