### ISSUE TITLE
Android - Main Page design implementation

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#371]
As discussed in this [issue](https://github.com/bounswe/2021SpringGroup6/issues/365), the main page(the page which will be displayed after user logins) will be reviewed and implemented.

**Comment by omersuve** [comment]
As we conclude , the Main page should consist of 3 fragment pages which are Home, Profile and Search pages.

**Comment by kataparuto** [comment]
The main page is implemented as it was discussed and designed. The tabbar is integrated to main page. The related [PR](https://github.com/bounswe/2021SpringGroup6/pull/377). The related [commit](https://github.com/bounswe/2021SpringGroup6/pull/377/commits/9be131e99a0c91cd7573906cfd6cbce378da84a5)
