### ISSUE TITLE
Android - Use Fragments instead of Activities

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#373]
Instead of multiple activities, fragments should be used. There should be multiple fragments in one single activity. This architecture change will make the app much more efficient because in Android, activities are heavier than fragments.

**Comment by omersuve** [comment]
We have decided in [this issue](https://github.com/bounswe/2021SpringGroup6/issues/361) that Using Fragments would not only benefit regarding performance but also benefit for ease of sturcture implemetation.

**Comment by kataparuto** [comment]
HomeFragment is created as the first fragment. The related (PR)[https://github.com/bounswe/2021SpringGroup6/pull/377] and the related (commit)[https://github.com/bounswe/2021SpringGroup6/pull/377/commits/9be131e99a0c91cd7573906cfd6cbce378da84a5]

**Comment by kataparuto** [comment]
The usage of Fragments instead of using only Activities are successfully integrated into our application. The related Pull Requests : https://github.com/bounswe/2021SpringGroup6/pull/392 https://github.com/bounswe/2021SpringGroup6/pull/398 https://github.com/bounswe/2021SpringGroup6/pull/400 https://github.com/bounswe/2021SpringGroup6/pull/404 
The related commits: 
https://github.com/bounswe/2021SpringGroup6/pull/392/commits/aa386b5b1b773c61212cc28b61a283681eab66b1
https://github.com/bounswe/2021SpringGroup6/pull/398/commits/0f86154dc583ccaa4be045c5c8cb2c09f6f2d99b
https://github.com/bounswe/2021SpringGroup6/pull/400/commits/5cca9528e5d13efeff334e8ee3d2da5af6bcbd2a
https://github.com/bounswe/2021SpringGroup6/pull/404/commits/f5ab1f829ab2e7f6c6d87c432422b543fe6e6489

**Comment by kataparuto** [comment]
The PR for the creation of SearchFragment : https://github.com/bounswe/2021SpringGroup6/pull/392
