### ISSUE TITLE
Prepare a scenario for the final milestone

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#378]
The customer presentations are significant since they are the places where we can directly and extensively communicate with the customer. The final one is even more important since it represents the final version and level of work done about the project; consequently, we ought to focus on it and one of the most essential components for a presentation is having a well designed and prepared scenario. Therefore, prepare a scenario for the last milestone please. Some crucial points to pay attention are integrating the customer into the presentation as much as possible, finding realistic and meaningful use cases and making the presentation as interesting as possible for the listeners.

**Comment by salihozcelik** [comment]
I have prepared some baseline for the presentation. Let's meet with the android team and discuss about the milestone project.

**Comment by salihozcelik** [comment]
Let's meet again tomorrow morning for final preparation. Thanks.
