### ISSUE TITLE
Create a Sequence Diagram for Blocking a User

### ISSUE THREAD

**Issue by omersuve** [bounswe/2021SpringGroup6#38]

**Comment by berkatil** [comment]
I created a [one](https://github.com/bounswe/2021SpringGroup6/wiki/Sequence-Diagrams) and will improve based on the feedback that we will get today from our customer.

**Comment by berkatil** [comment]
It is finished by adding database operation

**Comment by omersuve** [comment]
It would be better if the link goes to directly your image.
