### ISSUE TITLE
Create a DB model For Equipments and add predefined equipment types into the system

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#383]
As we discussed, we will define the equipment types and users will add discussion into them.
The DB model should contain the equipment name, its related sports,its description and its wikidata

To add different equipments decathlon api may be used (see https://developers.decathlon.com/ )

**Comment by fileames** [comment]
After discussion with the front-end team, we decided to not have predefined equipments and users can create equipments freely. 
Database models can be found [here](https://github.com/bounswe/2021SpringGroup6/pull/411)
