### ISSUE TITLE
Android - User Profile Page design and showing user information 

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#391]
In the profile page, the information of the logged in use will be viewed. The user will be able to update her/his information and also will be able to delete her/his account in his/her profile page.

**Comment by omersuve** [comment]
Related Profile Design issue:
[issue](https://github.com/bounswe/2021SpringGroup6/issues/315)

**Comment by omersuve** [comment]
> In the profile page, the information of the logged in use will be viewed. The user will be able to update her/his information and also will be able to delete her/his account in his/her profile page.

I think that we should seperate the navigating, deleting and updating operations.
We may open three issues for these three tasks.

**Comment by kataparuto** [comment]
As Ömer suggested, this issue will be used for User Profile layout implementation.

**Comment by kataparuto** [comment]
The implementation is finished. The related [PR](https://github.com/bounswe/2021SpringGroup6/pull/404) is here.
