### ISSUE TITLE
Create Search Sequence Diagram

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#41]
Sequence diagram for search function should be created. Related to [Search an Event Scenario](https://github.com/bounswe/2021SpringGroup6/wiki/Search-an-Event-Scenario) and details can be found on the use case diagram.

**Comment by fileames** [comment]
[Sequence Diagram](https://github.com/bounswe/2021SpringGroup6/wiki/Sequence-Diagrams#4-searching-an-event) for search is created and added to wiki.

**Comment by eye-78** [comment]
Very clear. Thank you
