### ISSUE TITLE
Create equipment page

### ISSUE THREAD

**Issue by salihozcelik** [bounswe/2021SpringGroup6#414]
1.5.2.1.1 Users can access information and comments/discussions about the specific equipment and place via the equipment page.
Equipment page need to have 
- "About" tab :  basic information about the equipment on this page like "Location", "Related Sports" and "Description".
- "Disccussion" tab : for people to post their questions, talk about where to find the equipment.
Since this page is really similar to event page, @38programmer61 may implement it easily.

**Comment by 38programmer61** [comment]
I have implemented the corresponding page as intended. Now it can be reached in the deployed application since we have merged [the corresponding pull request](https://github.com/bounswe/2021SpringGroup6/pull/420). If you also think that everything is OK, you can close the issue.

**Comment by salihozcelik** [comment]
thanks
