### ISSUE TITLE
Search equipment

### ISSUE THREAD

**Issue by salihozcelik** [bounswe/2021SpringGroup6#415]
Any user shall be search equipments from equipments page. Since its a very similar with event page @38programmer61 may implement it.

**Comment by 38programmer61** [comment]
Implementation for that functionality has been completed. I have opened [a corresponding PR](https://github.com/bounswe/2021SpringGroup6/pull/432) and it was already merged, which means that it's available in the deployed version of the program; therefore, the task is completed as far as I understand, so you can close the issue if you have similar thoughts about the task.

**Comment by salihozcelik** [comment]
thanks
