### ISSUE TITLE
Preparing Discussion Page For Events In Front-end Part

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#427]
Events are the main components of our application and one of the most useful features that we may have for them is allowing users to communicate about the event which can also be called as the discussion page of the event. Prepare the front-end page of that feature. By using this page the users ought to be able to send messages and read the messages sent by other people who will also join the event. You can examine the [API Documentation](https://github.com/bounswe/2021SpringGroup6/wiki/Squad-Game-API-Documentation) in order to get a better understanding.

**Comment by salihozcelik** [comment]
Discussion page for event is implemented. see ( https://github.com/bounswe/2021SpringGroup6/pull/460 )
