### ISSUE TITLE
Discussion Page For Equipment

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#433]
Having a discussion page is useful not only for events but also for equipments since they may require a certain type of communication too; therefore, implementing that part is beneficial too. Because we are planning to implement discussion page of the event, it had better be easier for us to implement that one. Again you can examine [the related API documentation](https://github.com/bounswe/2021SpringGroup6/wiki/Squad-Game-API-Documentation#equipmentsequipment_iddiscussion-get---get-equipment-posts) for getting more familiar with the task.

**Comment by salihozcelik** [comment]
Discussion page for equipment is implemented. see ( https://github.com/bounswe/2021SpringGroup6/pull/460 )
