### ISSUE TITLE
Bug fix for search equipment

### ISSUE THREAD

**Issue by salihozcelik** [bounswe/2021SpringGroup6#434]
search equipment page doesn't work, when I try to post new equipment, it says : Incorrect input. Try again.

**Comment by salihozcelik** [comment]
example input was :
balta, fighting, balta2
balta, fighting, +9balta

**Comment by 38programmer61** [comment]
It looks like the problem arises when you try to open a new equipment without giving an image related with it.

**Comment by 38programmer61** [comment]
It ought to be fixed now with [the pull request](https://github.com/bounswe/2021SpringGroup6/pull/435). We can close the issue I guess.

**Comment by salihozcelik** [comment]
thanks
