### ISSUE TITLE
Implementing Notification Page

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#441]
We need to provide notification function for our users. It does not have to be a real time function, but the web application should check for new notifications regularly. You may implement it by adding a "setinterval" inside a "useeffect" function to wrapper "app.js" file. Notifcation page should display new notifications in a list. When a new notification is sent, you may display it with a red sign on the notification page icon

**Comment by salihozcelik** [comment]
Notification page is implemented. see ( https://github.com/bounswe/2021SpringGroup6/pull/459 )
