### ISSUE TITLE
Create Wiki Page For Practice App API Documentation

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#53]
A page should be created with to document API functionalities as discussed [here](https://github.com/bounswe/2021SpringGroup6/wiki/Back-End-Meeting-1).

**Comment by fileames** [comment]
I created the template and wrote my endpoint documentation [here](https://github.com/bounswe/2021SpringGroup6/wiki/Practice-app-API-Documentation).

**Comment by eye-78** [comment]
Thank you. I used it and added my parts accordingy
