### ISSUE TITLE
Create the Front-end Pard for Adding a Badge

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#60]
Web page will be created to add a badge into the system. It will use the endpoint created on the following issue:
https://github.com/bounswe/2021SpringGroup6/issues/59

**Comment by berkatil** [comment]
IT is added on branch https://github.com/bounswe/2021SpringGroup6/tree/badge_add

**Comment by eye-78** [comment]
saw it an tested. nice job. thank you
