### ISSUE TITLE
GET operation for discussion and corresponding front-end page

### ISSUE THREAD

**Issue by 38programmer61** [bounswe/2021SpringGroup6#62]
It should be done by following the guidelines of the assignment description paper.

**Comment by 38programmer61** [comment]
It has been coded by adding the comments and API documentation using swagger. Corresponding front-end was also done. All of the content is in the repo now.

**Comment by 38programmer61** [comment]
The system is also in deployment; therefore, it is Ok now.

**Comment by eye-78** [comment]
Thank you for your effort and final product
