### ISSUE TITLE
Create a GET endpoint for events with their ID

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#65]
/api/v1.0/events/<event_id>  GET endpoint will be created to view an event, given its ID.

**Comment by kataparuto** [comment]
For the weather information, I have used the API https://openweathermap.org/current .

**Comment by kataparuto** [comment]
It has been added to the branch : https://github.com/bounswe/2021SpringGroup6/tree/event_search_by_id

**Comment by kataparuto** [comment]
I have also implemented the front-end part. I did a pull request. Then I corrected the conflicts and did the necessary changes according to the reviews of my teammates. Finally, I merged my branch(event_search_by_id branch) with the master branch.

**Comment by eye-78** [comment]
saw all of them. reviewed your code. seems nice, thank you. can you share your api key privately so that i can test your part
