### ISSUE TITLE
Prepare Personal Milestone 2 - Individual Deliverable

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#68]
Following parts should be written:

- [x] Executive summary
- [x] API
- [x] Code review
- [x] Pull requests
- [x] Issues
- [x] API documentation

**Comment by eye-78** [comment]
I think this can be assigned to all of us

**Comment by fileames** [comment]
I think everyone can create one issue separately so that individual progress would be easier to track.

**Comment by fileames** [comment]
Executive summary is written.

**Comment by fileames** [comment]
I wrote the APIs used part and commented on Google Maps Geocoding API and the Sports DB API.

**Comment by fileames** [comment]
The code review section is written, every review I made is added with relevant pull request and conversation.

**Comment by fileames** [comment]
The report is submitted. This was a very useful project and probably the one I learned the most. 
I learned new technologies such as Flask and Docker but also group communication, documentation, and more. I cannot wait to implement the big project next year.
