### ISSUE TITLE
Build get endpoint for api/v1/events

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#76]
- [x] read examples and tutorials
- [x] prepare your plan
- [x] get align with others' mothodologies
- [x] build your part

**Comment by eye-78** [comment]
- [ ] read two articles and prepared for building
- [ ] prepared plan did not match with others' plans
- [ ] got align with @fileames 's structure
- [ ] builded my part in api/events.py file
https://github.com/bounswe/2021SpringGroup6/tree/event_search

**Comment by fileames** [comment]
Filtering is a very important feature of our application, thanks for your effort.
