### ISSUE TITLE
Write unit tests for badge post endpoint

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#86]
It should just check if the status code of the response is 201

**Comment by berkatil** [comment]
The structure of the unittests is changed after the meeting with our customer. Followings should be checked for api/v1.0/badges endpoint
- Badge Creation is done successfully given the parameters.
- Point extraction from a bitcoin price is done successfully.

**Comment by berkatil** [comment]
I wrote them and merged them on [PR 92](https://github.com/bounswe/2021SpringGroup6/pull/92)

**Comment by eye-78** [comment]
All done well. Thank you!
