### ISSUE TITLE
Correct Response Code 403-503

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#90]
I think we all wrote response code 403 for request that cannot be handled by the server maybe due to not communicating with the external API. But I think since 430 is "Forbidden" and 503 is "Service Unavailable", we should change them to 503. What do you think?

**Comment by eye-78** [comment]
i'll take a look at it later that day. thank you

**Comment by eye-78** [comment]
you are right and some of us had changed their code. do you suggest the change to be mandatory?

**Comment by fileames** [comment]
I think everyone who thinks they used it wrong should change.

**Comment by bnbcfyh** [comment]
Correct, should use 503 instead of 403.

**Comment by kataparuto** [comment]
The problem seems to be resolved. Thanks everyone for their contribution and help.
