### ISSUE TITLE
Document tools that we used

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#95]
Followings must be stated:

1. Github
2. Flask
3. Whatsapp
4. Zoom
5. Google Meets
6. Google Docs
7. SqlAlchemy
8. Jinja
9. Bootstrap
10. Swagger
11. Docker
12. Postman

**Comment by eye-78** [comment]
I took it from where you left. You can see [here](https://docs.google.com/document/d/18h_tSLL-ozRxbWTddxjbscwqDCv9LiqVZV7egKG3mhk/edit#heading=h.1df0s7p06b00)

**Comment by fileames** [comment]
Added Google Docs. Also added some comments on Swagger.

**Comment by bnbcfyh** [comment]
Also, AWS can be added as we talked in one of the meetings.

**Comment by fileames** [comment]
Since the documentation is created (can be found [here](https://github.com/bounswe/2021SpringGroup6/blob/master/deliverables/M2_Report_Group6.pdf)), this issue can be closed. Tools used are explained in detail.
