### ISSUE TITLE
Write the Personal Milestone Report 2

### ISSUE THREAD

**Issue by berkatil** [bounswe/2021SpringGroup6#96]
- [x] Executive Summary
- [x] API
- [x] Code Review
- [x] Pull Request
- [x] Issue
- [x] API Documentation

**Comment by eye-78** [comment]
Nice format, I am copying you

**Comment by berkatil** [comment]
API part is almost finished except API documentation and sample call. I do not understand what to write for them exactly so I will ask tomorrow.

**Comment by berkatil** [comment]
Code review part is done.

**Comment by berkatil** [comment]
Pull request part is also done

**Comment by berkatil** [comment]
API part is finished

**Comment by berkatil** [comment]
All of them are finished. I just need to do proofreading

**Comment by eye-78** [comment]
Nice work. Thank you
